### ISSUE TITLE
runnig create_data.py

### ISSUE THREAD

**Issue by ashkanalinejad** [ondrejklejch/ctc#1]
Dear Mr Ondrej,

I'm trying to understand your code, but I cannot figure out what is contained in "/ha/work/people/klejch/test.wav"

Is it just an empty .wav file ?

**Comment by ondrejklejch** [comment]
Hi Ashkan,

"/ha/work/people/klejch/test.wav" is just a path to which I convert sphere file from TIMIT dataset to be able to read it as a normal wav file. You can replace the path with whatever you want.

**Comment by ashkanalinejad** [comment]
Cool. Thanks. Now create-data.py is running for more than one day (with only one CPU). Is it usual or am I doing sth wrong?!

**Comment by ondrejklejch** [comment]
It should not take that long. Are you using TIMIT?

**Comment by ashkanalinejad** [comment]
Yes. I'm using TIMIT. Well, I will recheck the procedure and I will put results here.
